update last sources 11.x series to master
update last sources 11.x series to master

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -6,7 +6,7 @@
 #
 # Run file system checks
 #
-# $FreeBSD: /etc/rc.d/fsck Revision 289186
+# $FreeBSD: /etc/rc.d/fsck	Revision 298514
 #
 # NAS4Free Changes: - Refactor fsck_start to process configured disks only.
 # 	   	    - Add fsck_start_root to check root file system on 'full' installations.
@@ -70,7 +70,21 @@ fsck_start()
 				fsck -p -t ${_fstype} ${_devicespecialfile}
 			fi
 
-			case $? in
+		err=$?
+		if [ ${err} -eq 3 ]; then
+			echo "Warning! Some of the devices might not be" \
+			    "available; retrying"
+			root_hold_wait
+			check_startmsgs && echo "Restarting file system checks:"
+			if checkyesno background_fsck; then
+				fsck -F -p
+			else
+				fsck -p
+			fi
+			err=$?
+		fi
+
+		case ${err} in
 			0)
 				;;
 			2)
@@ -107,7 +121,7 @@ fsck_start()
 				stop_boot
 				;;
 			*)
-				echo "Unknown error; help!"
+				echo "Unknown error ${err}; help!"
 				stop_boot
 				;;
 			esac
